### PR TITLE
Fixing UTF8 Errors

### PR DESCRIPTION
**Pull request by koconder**
UTF8 Errors on Mac OSX Terminal Python 2.7.10 breaking run

### CODE REVIEW

**Comment by manwhoami** [comment]
Hey, thanks for this. I will be happy to merge this if you would please fix your changes to be PEP8 compliant (specifically the <80 chars per line specification, and removing whitespaces before any ")"). Thanks!

**Comment by koconder** [comment]
@manwhoami PEP8 compliance added, please review and merge

**Comment by dotysan** [comment]
```Traceback (most recent call last):
  File "chrome_passwords.py", line 231, in <module>
    chrome(chrome_data, safe_storage_key)
  File "chrome_passwords.py", line 190, in chrome
    utfout(entry["exp_m"]),
  File "chrome_passwords.py", line 134, in utfout
    return inputvar.encode("utf-8", errors="replace")
AttributeError: 'int' object has no attribute 'encode'
```

Ooccurs on both exp_m and exp_y. Workaround is to remove the utfout() for those 2 vars.

**Comment by koconder** [comment]
@dotysan i just fixed on my own repo, using some additional conditional checks for the format of the content first before outputting, should also be back compatible python 2 vs. 3. https://github.com/koconder/OSXChromeDecrypt/commit/63d3a0f4191507d440f361916993a32dc1fda009 - Will raise another PR for the fix

**Pull request merged**
